# save this as aws-auth.yaml and apply with kubectl apply -f aws-auth.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::183315836917:role/githubrole
      username: github-actions
      groups:
        - system:masters
